import os
from building import *

src = []
objs = []
cwd  = GetCurrentDir()
CPPPATH = [cwd]

src += Glob('*.c')

objs = DefineGroup('usb_pcdc', src, depend = ['BSP_USING_USB_PCDC'], CPPPATH = CPPPATH)

Return('objs')
