/* generated vector source file - do not edit */
        #include "bsp_api.h"
        /* Do not build these data structures if no interrupts are currently allocated because IAR will have build errors. */
        #if VECTOR_DATA_IRQ_COUNT > 0
        BSP_DONT_REMOVE const fsp_vector_t g_vector_table[BSP_ICU_VECTOR_NUM_ENTRIES] BSP_PLACE_IN_SECTION(BSP_SECTION_APPLICATION_VECTORS) =
        {
                        [0] = sci_b_uart_rxi_isr, /* SCI5 RXI (Receive data full) */
            [1] = sci_b_uart_txi_isr, /* SCI5 TXI (Transmit data empty) */
            [2] = sci_b_uart_tei_isr, /* SCI5 TEI (Transmit end) */
            [3] = sci_b_uart_eri_isr, /* SCI5 ERI (Receive error) */
            [4] = ipc_isr, /* IPC IRQ1 (CPU Mutual Interrupt 1) */
            [5] = sci_b_uart_rxi_isr, /* SCI0 RXI (Receive data full) */
            [6] = sci_b_uart_txi_isr, /* SCI0 TXI (Transmit data empty) */
            [7] = sci_b_uart_tei_isr, /* SCI0 TEI (Transmit end) */
            [8] = sci_b_uart_eri_isr, /* SCI0 ERI (Receive error) */
            [9] = sdhimmc_accs_isr, /* SDHIMMC1 ACCS (Card access) */
            [10] = sdhimmc_card_isr, /* SDHIMMC1 CARD (Card detect) */
            [11] = dmac_int_isr, /* DMAC1 INT (DMAC1 transfer end) */
            [12] = sdhimmc_accs_isr, /* SDHIMMC0 ACCS (Card access) */
            [13] = sdhimmc_card_isr, /* SDHIMMC0 CARD (Card detect) */
            [14] = dmac_int_isr, /* DMAC2 INT (DMAC2 transfer end) */
            [15] = sci_b_uart_rxi_isr, /* SCI8 RXI (Receive data full) */
            [16] = sci_b_uart_txi_isr, /* SCI8 TXI (Transmit data empty) */
            [17] = sci_b_uart_tei_isr, /* SCI8 TEI (Transmit end) */
            [18] = sci_b_uart_eri_isr, /* SCI8 ERI (Receive error) */
            [19] = iic_master_rxi_isr, /* IIC0 RXI (Receive data full) */
            [20] = iic_master_txi_isr, /* IIC0 TXI (Transmit data empty) */
            [21] = iic_master_tei_isr, /* IIC0 TEI (Transmit end) */
            [22] = iic_master_eri_isr, /* IIC0 ERI (Transfer error) */
            [23] = glcdc_line_detect_isr, /* GLCDC LINE DETECT (Specified line) */
            [24] = drw_int_isr, /* DRW INT (DRW interrupt) */
            [25] = layer3_switch_gwdi_isr, /* ETHER GWDI0 (GWCA Data Interrupt 0) */
            [26] = sci_b_uart_rxi_isr, /* SCI9 RXI (Receive data full) */
            [27] = sci_b_uart_txi_isr, /* SCI9 TXI (Transmit data empty) */
            [28] = sci_b_uart_tei_isr, /* SCI9 TEI (Transmit end) */
            [29] = sci_b_uart_eri_isr, /* SCI9 ERI (Receive error) */
            [30] = gpt_counter_overflow_isr, /* GPT0 COUNTER OVERFLOW (Overflow) */
            [31] = gpt_counter_overflow_isr, /* GPT1 COUNTER OVERFLOW (Overflow) */
            [32] = iic_master_rxi_isr, /* IIC2 RXI (Receive data full) */
            [33] = iic_master_txi_isr, /* IIC2 TXI (Transmit data empty) */
            [34] = iic_master_tei_isr, /* IIC2 TEI (Transmit end) */
            [35] = iic_master_eri_isr, /* IIC2 ERI (Transfer error) */
            [36] = canfd_error_isr, /* CAN0 CHERR (Channel  error) */
            [37] = canfd_channel_tx_isr, /* CAN0 TX (Transmit interrupt) */
            [38] = canfd_common_fifo_rx_isr, /* CAN0 COMFRX (Common FIFO receive interrupt) */
            [39] = canfd_error_isr, /* CAN GLERR (Global error) */
            [40] = canfd_rx_fifo_isr, /* CAN RXF (Global receive FIFO interrupt) */
            [41] = canfd_error_isr, /* CAN1 CHERR (Channel  error) */
            [42] = canfd_channel_tx_isr, /* CAN1 TX (Transmit interrupt) */
            [43] = canfd_common_fifo_rx_isr, /* CAN1 COMFRX (Common FIFO receive interrupt) */
            [44] = spi_b_rxi_isr, /* SPI0 RXI (Receive buffer full) */
            [45] = spi_b_txi_isr, /* SPI0 TXI (Transmit buffer empty) */
            [46] = spi_b_tei_isr, /* SPI0 TEI (Transmission complete event) */
            [47] = spi_b_eri_isr, /* SPI0 ERI (Error) */
            [48] = rtc_alarm_periodic_isr, /* RTC ALARM (Alarm interrupt) */
            [49] = rtc_alarm_periodic_isr, /* RTC PERIOD (Periodic interrupt) */
            [50] = rtc_carry_isr, /* RTC CARRY (Carry interrupt) */
            [51] = r_icu_isr, /* ICU IRQ20 (External pin interrupt 20) */
            [52] = r_icu_isr, /* ICU IRQ13 (External pin interrupt 13) */
            [53] = adc_b_limclpi_isr, /* ADC LIMCLPI (Limiter clip interrupt with the limit table 0 to 7) */
            [54] = adc_b_err0_isr, /* ADC ERR0 (A/D converter unit 0 Error) */
            [55] = adc_b_err1_isr, /* ADC ERR1 (A/D converter unit 1 Error) */
            [56] = adc_b_resovf0_isr, /* ADC RESOVF0 (A/D conversion overflow on A/D converter unit 0) */
            [57] = adc_b_resovf1_isr, /* ADC RESOVF1 (A/D conversion overflow on A/D converter unit 1) */
            [58] = adc_b_calend0_isr, /* ADC CALEND0 (End of calibration of A/D converter unit 0) */
            [59] = adc_b_calend1_isr, /* ADC CALEND1 (End of calibration of A/D converter unit 1) */
            [60] = adc_b_adi0_isr, /* ADC ADI0 (End of A/D scanning operation(Gr.0)) */
            [61] = adc_b_adi1_isr, /* ADC ADI1 (End of A/D scanning operation(Gr.1)) */
            [62] = adc_b_adi2_isr, /* ADC ADI2 (End of A/D scanning operation(Gr.2)) */
            [63] = adc_b_adi3_isr, /* ADC ADI3 (End of A/D scanning operation(Gr.3)) */
            [64] = adc_b_adi4_isr, /* ADC ADI4 (End of A/D scanning operation(Gr.4)) */
            [65] = adc_b_fifoovf_isr, /* ADC FIFOOVF (FIFO data overflow) */
            [66] = adc_b_fiforeq0_isr, /* ADC FIFOREQ0 (FIFO data read request interrupt(Gr.0)) */
            [67] = adc_b_fiforeq1_isr, /* ADC FIFOREQ1 (FIFO data read request interrupt(Gr.1)) */
            [68] = adc_b_fiforeq2_isr, /* ADC FIFOREQ2 (FIFO data read request interrupt(Gr.2)) */
            [69] = adc_b_fiforeq3_isr, /* ADC FIFOREQ3 (FIFO data read request interrupt(Gr.3)) */
            [70] = adc_b_fiforeq4_isr, /* ADC FIFOREQ4 (FIFO data read request interrupt(Gr.4)) */
            [71] = vin_status_isr, /* VIN IRQ (Interrupt Request) */
            [72] = vin_error_isr, /* VIN ERR (Interrupt Request for SYNC Error) */
            [73] = mipi_csi_rx_isr, /* MIPICSI RX (Receive interrupt) */
            [74] = mipi_csi_dl_isr, /* MIPICSI DL (Data Lane interrupt) */
            [75] = mipi_csi_vc_isr, /* MIPICSI VC (Virtual Channel interrupt) */
            [76] = mipi_csi_pm_isr, /* MIPICSI PM (Power Management interrupt) */
            [77] = mipi_csi_gst_isr, /* MIPICSI GST (Generic Short Packet interrupt) */
        };
        #if BSP_FEATURE_ICU_HAS_IELSR
        const bsp_interrupt_event_t g_interrupt_event_link_select[BSP_ICU_VECTOR_NUM_ENTRIES] =
        {
            [0] = BSP_PRV_VECT_ENUM(EVENT_SCI5_RXI,GROUP0), /* SCI5 RXI (Receive data full) */
            [1] = BSP_PRV_VECT_ENUM(EVENT_SCI5_TXI,GROUP1), /* SCI5 TXI (Transmit data empty) */
            [2] = BSP_PRV_VECT_ENUM(EVENT_SCI5_TEI,GROUP2), /* SCI5 TEI (Transmit end) */
            [3] = BSP_PRV_VECT_ENUM(EVENT_SCI5_ERI,GROUP3), /* SCI5 ERI (Receive error) */
            [4] = BSP_PRV_VECT_ENUM(EVENT_IPC_IRQ1,GROUP4), /* IPC IRQ1 (CPU Mutual Interrupt 1) */
            [5] = BSP_PRV_VECT_ENUM(EVENT_SCI0_RXI,GROUP5), /* SCI0 RXI (Receive data full) */
            [6] = BSP_PRV_VECT_ENUM(EVENT_SCI0_TXI,GROUP6), /* SCI0 TXI (Transmit data empty) */
            [7] = BSP_PRV_VECT_ENUM(EVENT_SCI0_TEI,GROUP7), /* SCI0 TEI (Transmit end) */
            [8] = BSP_PRV_VECT_ENUM(EVENT_SCI0_ERI,GROUP0), /* SCI0 ERI (Receive error) */
            [9] = BSP_PRV_VECT_ENUM(EVENT_SDHIMMC1_ACCS,GROUP1), /* SDHIMMC1 ACCS (Card access) */
            [10] = BSP_PRV_VECT_ENUM(EVENT_SDHIMMC1_CARD,GROUP2), /* SDHIMMC1 CARD (Card detect) */
            [11] = BSP_PRV_VECT_ENUM(EVENT_DMAC1_INT,GROUP3), /* DMAC1 INT (DMAC1 transfer end) */
            [12] = BSP_PRV_VECT_ENUM(EVENT_SDHIMMC0_ACCS,GROUP4), /* SDHIMMC0 ACCS (Card access) */
            [13] = BSP_PRV_VECT_ENUM(EVENT_SDHIMMC0_CARD,GROUP5), /* SDHIMMC0 CARD (Card detect) */
            [14] = BSP_PRV_VECT_ENUM(EVENT_DMAC2_INT,GROUP6), /* DMAC2 INT (DMAC2 transfer end) */
            [15] = BSP_PRV_VECT_ENUM(EVENT_SCI8_RXI,GROUP7), /* SCI8 RXI (Receive data full) */
            [16] = BSP_PRV_VECT_ENUM(EVENT_SCI8_TXI,GROUP0), /* SCI8 TXI (Transmit data empty) */
            [17] = BSP_PRV_VECT_ENUM(EVENT_SCI8_TEI,GROUP1), /* SCI8 TEI (Transmit end) */
            [18] = BSP_PRV_VECT_ENUM(EVENT_SCI8_ERI,GROUP2), /* SCI8 ERI (Receive error) */
            [19] = BSP_PRV_VECT_ENUM(EVENT_IIC0_RXI,GROUP3), /* IIC0 RXI (Receive data full) */
            [20] = BSP_PRV_VECT_ENUM(EVENT_IIC0_TXI,GROUP4), /* IIC0 TXI (Transmit data empty) */
            [21] = BSP_PRV_VECT_ENUM(EVENT_IIC0_TEI,GROUP5), /* IIC0 TEI (Transmit end) */
            [22] = BSP_PRV_VECT_ENUM(EVENT_IIC0_ERI,GROUP6), /* IIC0 ERI (Transfer error) */
            [23] = BSP_PRV_VECT_ENUM(EVENT_GLCDC_LINE_DETECT,GROUP7), /* GLCDC LINE DETECT (Specified line) */
            [24] = BSP_PRV_VECT_ENUM(EVENT_DRW_INT,GROUP0), /* DRW INT (DRW interrupt) */
            [25] = BSP_PRV_VECT_ENUM(EVENT_ETHER_GWDI0,GROUP1), /* ETHER GWDI0 (GWCA Data Interrupt 0) */
            [26] = BSP_PRV_VECT_ENUM(EVENT_SCI9_RXI,GROUP2), /* SCI9 RXI (Receive data full) */
            [27] = BSP_PRV_VECT_ENUM(EVENT_SCI9_TXI,GROUP3), /* SCI9 TXI (Transmit data empty) */
            [28] = BSP_PRV_VECT_ENUM(EVENT_SCI9_TEI,GROUP4), /* SCI9 TEI (Transmit end) */
            [29] = BSP_PRV_VECT_ENUM(EVENT_SCI9_ERI,GROUP5), /* SCI9 ERI (Receive error) */
            [30] = BSP_PRV_VECT_ENUM(EVENT_GPT0_COUNTER_OVERFLOW,GROUP6), /* GPT0 COUNTER OVERFLOW (Overflow) */
            [31] = BSP_PRV_VECT_ENUM(EVENT_GPT1_COUNTER_OVERFLOW,GROUP7), /* GPT1 COUNTER OVERFLOW (Overflow) */
            [32] = BSP_PRV_VECT_ENUM(EVENT_IIC2_RXI,FIXED), /* IIC2 RXI (Receive data full) */
            [33] = BSP_PRV_VECT_ENUM(EVENT_IIC2_TXI,FIXED), /* IIC2 TXI (Transmit data empty) */
            [34] = BSP_PRV_VECT_ENUM(EVENT_IIC2_TEI,FIXED), /* IIC2 TEI (Transmit end) */
            [35] = BSP_PRV_VECT_ENUM(EVENT_IIC2_ERI,FIXED), /* IIC2 ERI (Transfer error) */
            [36] = BSP_PRV_VECT_ENUM(EVENT_CAN0_CHERR,FIXED), /* CAN0 CHERR (Channel  error) */
            [37] = BSP_PRV_VECT_ENUM(EVENT_CAN0_TX,FIXED), /* CAN0 TX (Transmit interrupt) */
            [38] = BSP_PRV_VECT_ENUM(EVENT_CAN0_COMFRX,FIXED), /* CAN0 COMFRX (Common FIFO receive interrupt) */
            [39] = BSP_PRV_VECT_ENUM(EVENT_CAN_GLERR,FIXED), /* CAN GLERR (Global error) */
            [40] = BSP_PRV_VECT_ENUM(EVENT_CAN_RXF,FIXED), /* CAN RXF (Global receive FIFO interrupt) */
            [41] = BSP_PRV_VECT_ENUM(EVENT_CAN1_CHERR,FIXED), /* CAN1 CHERR (Channel  error) */
            [42] = BSP_PRV_VECT_ENUM(EVENT_CAN1_TX,FIXED), /* CAN1 TX (Transmit interrupt) */
            [43] = BSP_PRV_VECT_ENUM(EVENT_CAN1_COMFRX,FIXED), /* CAN1 COMFRX (Common FIFO receive interrupt) */
            [44] = BSP_PRV_VECT_ENUM(EVENT_SPI0_RXI,FIXED), /* SPI0 RXI (Receive buffer full) */
            [45] = BSP_PRV_VECT_ENUM(EVENT_SPI0_TXI,FIXED), /* SPI0 TXI (Transmit buffer empty) */
            [46] = BSP_PRV_VECT_ENUM(EVENT_SPI0_TEI,FIXED), /* SPI0 TEI (Transmission complete event) */
            [47] = BSP_PRV_VECT_ENUM(EVENT_SPI0_ERI,FIXED), /* SPI0 ERI (Error) */
            [48] = BSP_PRV_VECT_ENUM(EVENT_RTC_ALARM,FIXED), /* RTC ALARM (Alarm interrupt) */
            [49] = BSP_PRV_VECT_ENUM(EVENT_RTC_PERIOD,FIXED), /* RTC PERIOD (Periodic interrupt) */
            [50] = BSP_PRV_VECT_ENUM(EVENT_RTC_CARRY,FIXED), /* RTC CARRY (Carry interrupt) */
            [51] = BSP_PRV_VECT_ENUM(EVENT_ICU_IRQ20,FIXED), /* ICU IRQ20 (External pin interrupt 20) */
            [52] = BSP_PRV_VECT_ENUM(EVENT_ICU_IRQ13,FIXED), /* ICU IRQ13 (External pin interrupt 13) */
            [53] = BSP_PRV_VECT_ENUM(EVENT_ADC_LIMCLPI,FIXED), /* ADC LIMCLPI (Limiter clip interrupt with the limit table 0 to 7) */
            [54] = BSP_PRV_VECT_ENUM(EVENT_ADC_ERR0,FIXED), /* ADC ERR0 (A/D converter unit 0 Error) */
            [55] = BSP_PRV_VECT_ENUM(EVENT_ADC_ERR1,FIXED), /* ADC ERR1 (A/D converter unit 1 Error) */
            [56] = BSP_PRV_VECT_ENUM(EVENT_ADC_RESOVF0,FIXED), /* ADC RESOVF0 (A/D conversion overflow on A/D converter unit 0) */
            [57] = BSP_PRV_VECT_ENUM(EVENT_ADC_RESOVF1,FIXED), /* ADC RESOVF1 (A/D conversion overflow on A/D converter unit 1) */
            [58] = BSP_PRV_VECT_ENUM(EVENT_ADC_CALEND0,FIXED), /* ADC CALEND0 (End of calibration of A/D converter unit 0) */
            [59] = BSP_PRV_VECT_ENUM(EVENT_ADC_CALEND1,FIXED), /* ADC CALEND1 (End of calibration of A/D converter unit 1) */
            [60] = BSP_PRV_VECT_ENUM(EVENT_ADC_ADI0,FIXED), /* ADC ADI0 (End of A/D scanning operation(Gr.0)) */
            [61] = BSP_PRV_VECT_ENUM(EVENT_ADC_ADI1,FIXED), /* ADC ADI1 (End of A/D scanning operation(Gr.1)) */
            [62] = BSP_PRV_VECT_ENUM(EVENT_ADC_ADI2,FIXED), /* ADC ADI2 (End of A/D scanning operation(Gr.2)) */
            [63] = BSP_PRV_VECT_ENUM(EVENT_ADC_ADI3,FIXED), /* ADC ADI3 (End of A/D scanning operation(Gr.3)) */
            [64] = BSP_PRV_VECT_ENUM(EVENT_ADC_ADI4,FIXED), /* ADC ADI4 (End of A/D scanning operation(Gr.4)) */
            [65] = BSP_PRV_VECT_ENUM(EVENT_ADC_FIFOOVF,FIXED), /* ADC FIFOOVF (FIFO data overflow) */
            [66] = BSP_PRV_VECT_ENUM(EVENT_ADC_FIFOREQ0,FIXED), /* ADC FIFOREQ0 (FIFO data read request interrupt(Gr.0)) */
            [67] = BSP_PRV_VECT_ENUM(EVENT_ADC_FIFOREQ1,FIXED), /* ADC FIFOREQ1 (FIFO data read request interrupt(Gr.1)) */
            [68] = BSP_PRV_VECT_ENUM(EVENT_ADC_FIFOREQ2,FIXED), /* ADC FIFOREQ2 (FIFO data read request interrupt(Gr.2)) */
            [69] = BSP_PRV_VECT_ENUM(EVENT_ADC_FIFOREQ3,FIXED), /* ADC FIFOREQ3 (FIFO data read request interrupt(Gr.3)) */
            [70] = BSP_PRV_VECT_ENUM(EVENT_ADC_FIFOREQ4,FIXED), /* ADC FIFOREQ4 (FIFO data read request interrupt(Gr.4)) */
            [71] = BSP_PRV_VECT_ENUM(EVENT_VIN_IRQ,FIXED), /* VIN IRQ (Interrupt Request) */
            [72] = BSP_PRV_VECT_ENUM(EVENT_VIN_ERR,FIXED), /* VIN ERR (Interrupt Request for SYNC Error) */
            [73] = BSP_PRV_VECT_ENUM(EVENT_MIPICSI_RX,FIXED), /* MIPICSI RX (Receive interrupt) */
            [74] = BSP_PRV_VECT_ENUM(EVENT_MIPICSI_DL,FIXED), /* MIPICSI DL (Data Lane interrupt) */
            [75] = BSP_PRV_VECT_ENUM(EVENT_MIPICSI_VC,FIXED), /* MIPICSI VC (Virtual Channel interrupt) */
            [76] = BSP_PRV_VECT_ENUM(EVENT_MIPICSI_PM,FIXED), /* MIPICSI PM (Power Management interrupt) */
            [77] = BSP_PRV_VECT_ENUM(EVENT_MIPICSI_GST,FIXED), /* MIPICSI GST (Generic Short Packet interrupt) */
        };
        #endif
        #endif