import os
from building import *

src = []
objs = []
cwd  = GetCurrentDir()
CPPPATH = [cwd]

src = Glob('*.c')

objs = DefineGroup('Drivers', src, depend = ['BSP_USING_MIPI_CSI_CAMERA'], CPPPATH = CPPPATH)

Return('objs')
